language: csharp
mono: none
dotnet: 3.1 
solution: Stack/Stack.sln
script:
- dotnet restore Stack/Stack.sln
- dotnet build Stack/Stack.sln
- dotnet test /Stack/NUnitTestStack/NUnitTestStack.csproj
on:
  tags: true
  branches:
    only:
      - master